- name: Deploy to BunnyCDN
  uses: ayeressian/bunnycdn-storage-deploy@v2.4.0
  with:
	source: "public"
	destination: "/"
	storageZoneName: "${{ secrets.STORAGE_NAME }}"
	storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
	accessKey: "${{ secrets.STORAGE_KEY }}"
	pullZoneId: "${{ secrets.ZONE_ID }}"
	upload: "true"
	remove: "true"
	purgePullZone: "true"
	purgePullZoneDelay: "5"
	maxRetries: "5"	