- name: BunnyCDN
  uses: ayeressian/bunnycdn-storage-deploy@v2.4.0
  with:
    source: public
    destination: /
    storageZoneName: "${{ secrets.BUNNY_STORAGE_NAME }}"
    storagePassword: "${{ secrets.BUNNY_STORAGE_PASSWORD }}"
    storageEndpoint: "${{ secrets.BUNNY_STORAGE_ENDPOINT }}"
    accessKey: "${{ secrets.BUNNY_API_KEY }}"
    pullZoneId: "${{ secrets.BUNNY_ZONE_ID }}"
    upload: "true"
    remove: "true"
    purgePullZone: "true"